# -*- coding: utf-8 -*-
"""sheetalbot_gsa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1656tL6klqmBYoGZmiI2jOHyg4CR3RB2x
"""

!pip install streamlit

import streamlit as st

# Page setup
st.set_page_config(
    page_title="SheetalBot – Google Student Ambassador 2025",
    page_icon="🤖",
    layout="centered"
)

# Custom Google-style CSS
st.markdown("""
    <style>
        .main {
            background-color: #ffffff;
            font-family: "Google Sans", "Segoe UI", sans-serif;
        }
        h1 {
            color: #4285F4;
            font-size: 2.5rem;
            text-align: center;
        }
        .stChatInputContainer {
            background-color: #f1f3f4;
        }
        .stMarkdown {
            font-size: 1rem;
        }
        .footer {
            text-align: center;
            color: #555;
            margin-top: 50px;
            font-size: 14px;
        }
    </style>
""", unsafe_allow_html=True)

# Title and introduction
st.title("🤖 SheetalBot – Your Google Student Ambassador 2025")
st.markdown("""
<div style="color:#0F9D58; font-size:18px;">
Hi, I’m <strong>SheetalBot</strong> – the virtual version of <strong>Sheetal Pandey</strong> 👩‍💻
Ask me anything about Google tools, AI, student communities, or why I’m the perfect fit to be a <strong>Google Student Ambassador 2025</strong>!
</div>
""", unsafe_allow_html=True)

st.divider()

# Store chat history
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

# Chatbot reply logic
def generate_reply(user_input):
    user_input = user_input.lower()

    if "who are you" in user_input or "your name" in user_input:
        return "I’m SheetalBot – your friendly tech guide, built by Sheetal Pandey, a passionate, community-driven student applying to be your Google Student Ambassador 2025! 😊"

    elif "why gsa" in user_input or "ambassador" in user_input:
        return ("Because I bridge students and technology. I empower my peers through workshops, Google tool training, and AI-powered mentoring. "
                "Being a GSA will let me create an even bigger impact.")

    elif "favorite google tool" in user_input or "fav tool" in user_input:
        return "Google Sheets! 📊 I love automating data workflows and teaching others how to make their data meaningful with simple tools."

    elif "ai" in user_input or "gemini" in user_input:
        return ("AI is the future, and I help students understand how to use Gemini for resumes, brainstorming, and project automation. "
                "As a GSA, I’ll promote responsible and creative use of Google AI tools.")

    elif "experience" in user_input or "what have you done" in user_input:
        return ("I've helped over 50 students understand Google tools, conducted hands-on bootcamps, built project dashboards, and simplified tech for non-tech users. "
                "Inclusivity + innovation = my mantra.")

    elif "real" in user_input:
        return "Well, I’m a bot — but Sheetal Pandey is very real, and she’s ready to lead, teach, and represent the next generation of student innovators. 🚀"

    elif "hi" in user_input or "hello" in user_input:
        return "Hey there! 👋 Excited to share all the reasons I’d make an impactful Google Student Ambassador!"

    elif "bye" in user_input or "goodbye" in user_input:
        return "Goodbye! Hope to connect soon — maybe as your GSA 2025. 💙💛💚❤️"

    else:
        return "I’m still learning! Try asking about Google tools, AI, or why Sheetal Pandey is the perfect GSA fit."

# Chat input
user_input = st.chat_input("Ask SheetalBot anything...")

if user_input:
    st.session_state.chat_history.append(("You", user_input))
    bot_reply = generate_reply(user_input)
    st.session_state.chat_history.append(("SheetalBot", bot_reply))

# Display the conversation
for sender, message in st.session_state.chat_history:
    if sender == "You":
        st.markdown(f"<div style='color:#EA4335;'><strong>You:</strong> {message}</div>", unsafe_allow_html=True)
    else:
        st.markdown(f"<div style='color:#4285F4;'><strong>🤖 SheetalBot:</strong> {message}</div>", unsafe_allow_html=True)

# Footer
st.markdown("""
<div class="footer">
Made with ❤️ using Streamlit · Inspired by Google's mission to make information universally accessible & useful
</div>
""", unsafe_allow_html=True)